set export
PROTOS_DIR := '../../contracts/protos'

clean:
  @echo "Cleaning GoLang code..."
  rm -rf ./go/pkg/*
  @echo "Cleaning Python code..."
  rm -rf ./python/*
  @echo "Cleaning JavaScript code..."
  rm -rf ./js/*

grpc-generate: clean
  @echo "Generating gRPC code..."
  buf generate ../../contracts/protos

grpc-lint:
  @echo "Linting gRPC code..."
  buf lint ../../contracts/protos
