name: API Contracts

on:
  push:
    branches:
      - main
    paths:
      - 'contracts/protos/**'
      - 'libs/grpc-collections/**'
      - '.github/workflows/api-contracts.yml'
  pull_request:
    paths:
      - 'contracts/protos/**'
      - 'libs/grpc-collections/**'
      - '.github/workflows/api-contracts.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: contracts/protos

      - name: Breaking
        uses: bufbuild/buf-breaking-action@v1
        if: github.event_name == 'pull_request'
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=contracts/protos'
          input: contracts/protos
