name: Platform CLI CI

on:
  push:
    branches:
      - main
    paths:
      - 'tools/platform-cli/**'
      - '.github/workflows/platform-cli.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/platform-cli/**'
      - '.github/workflows/platform-cli.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ github.workspace }}/tools/platform-cli
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: ${{ env.WORKING_DIR }}/go.mod
          cache-dependency-path: |
            ${{ env.WORKING_DIR }}/go.mod
            ${{ env.WORKING_DIR }}/go.sum

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o ./bin/platform-cli ./cmd/platform-cli

      - name: Upload artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          name: platform-cli
          path: ${{ env.WORKING_DIR }}/bin/platform-cli
