name: Platform CLI CI

on:
  push:
    branches:
      - main
    paths:
      - 'tools/platform-cli/**'
      - '.github/workflows/platform-cli.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/platform-cli/**'
      - '.github/workflows/platform-cli.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ github.workspace }}/tools/platform-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ env.WORKING_DIR }}/go.mod
          cache-dependency-path: |
            ${{ env.WORKING_DIR }}/go.mod
            ${{ env.WORKING_DIR }}/go.sum

      - name: Build
        run: go build -o ./bin/platform-cli ./cmd/platform-cli

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: platform-cli
          path: ./bin/platform-cli
